### ISSUE TITLE
Help Request

### ISSUE THREAD

**Issue by T7x** [Glis6/ActionManager#1]
Hallo Glis,

Ik ben op het moment bezig met een copy van ArteroPk Server
En zou graag PlayerLoading/Saving via MongoDB willen doen,
Zou jij mij misschien alsjeblieft mee helpen?

Bedank!

Groet,

T7emon

**Comment by Glis6** [comment]
Kan gedaan worden ja, waar heb je hulp mee nodig?

**Comment by T7x** [comment]
Ik heb PlayerSaving in mongo bijna klaar maar weet niet of ik het goed heb gedaan en inventory, bank saving is me nog niet helemaal gelukt en vroeg me af hoe ik playerloading via mongo doe.
Heb je misschien skype of een e-mail? Ik durf het project niet op github te zetten aangezien er een aantal mensen zijn die de server willen leechen.

Alvast bedank!

**Comment by Glis6** [comment]
gilleszs
